/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    LoadingSkeleton: typeof import('./src/components/LoadingSkeleton.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PriorityBadge: typeof import('./src/components/PriorityBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubTaskList: typeof import('./src/components/SubTaskList.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    TagChip: typeof import('./src/components/TagChip.vue')['default']
    TagSelector: typeof import('./src/components/TagSelector.vue')['default']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
    TaskFilter: typeof import('./src/components/TaskFilter.vue')['default']
    TaskForm: typeof import('./src/components/TaskForm.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
